# Generated by Django 2.0 on 2018-01-01 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the payment account', max_length=128)),
                ('abbreviation', models.CharField(help_text='The abbreviated name of the payment account', max_length=5)),
                ('icon', models.ImageField(blank=True, help_text='The icon of the payment account', null=True, upload_to='./media/paymentIcons')),
                ('is_active', models.BooleanField(default=True, help_text='Set whether the payment account is active or not.')),
                ('show_balance', models.BooleanField(default=True, help_text='Set whether for this account is shown.')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='The balance of the account.', max_digits=9)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Timestamp of when the transaction was last updated.', null=True)),
                ('account', models.OneToOneField(help_text='The account the balance has been computed for.', on_delete=django.db.models.deletion.CASCADE, to='transactions.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Set whether the category is active or not.')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the transaction')),
                ('description', models.CharField(help_text='The description of the transaction', max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of the transaction', max_digits=9)),
                ('action', models.IntegerField(choices=[(1, 'Credit'), (-1, 'Debit')], help_text='Set whether the transaction is a credit or debit.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the transaction was created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Timestamp of when the transaction was last updated.')),
                ('tax_deduction', models.BooleanField(default=False, help_text='Set whether the transaction is tax deductable.')),
                ('account', models.ForeignKey(help_text='The payment account used.', on_delete=django.db.models.deletion.PROTECT, to='transactions.Account')),
                ('category', models.ForeignKey(help_text='The category of the transaction.', on_delete=django.db.models.deletion.PROTECT, to='transactions.Category')),
                ('created_by', models.ForeignKey(help_text='The user who created the transaction.', on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='The user who last updated the transaction', on_delete=django.db.models.deletion.PROTECT, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user the transaction belongs to.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
